"""add sec_filings

8-K / 6-K filing text from SEC EDGAR, input for the catalyst extraction step.

Revision ID: 31b99dc785b4
Revises: 626671fc7c86
Create Date: 2026-10-03 20:22:04.797465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '31b99dc785b4'
down_revision: Union[str, None] = '626671fc7c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'sec_filings',
        sa.Column('accession_number', sa.String(length=25), nullable=False),
        sa.Column('ticker', sa.String(length=10), nullable=False),
        sa.Column('form', sa.String(length=10), nullable=False),
        sa.Column('items', sa.String(length=100), nullable=True),
        sa.Column('filed_date', sa.Date(), nullable=False),
        sa.Column('url', sa.String(length=500), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        # sa.false() instead of the autogenerated text('0'): postgres rejects an integer default on boolean
        sa.Column('processed', sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('accession_number'),
    )
    op.create_index('ix_sec_filings_ticker', 'sec_filings', ['ticker'])


def downgrade() -> None:
    op.drop_index('ix_sec_filings_ticker', table_name='sec_filings')
    op.drop_table('sec_filings')
